# Generated by Django 4.1.4 on 2022-12-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
