# Generated by Django 4.1.4 on 2022-12-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_product_amount_product_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
